"""Build es/index.html (Spanish) from index.html (English).

    python3 tools/build_es.py

index.html stays the single source for layout and markup. This script
swaps in the Spanish copy from es_strings.py and fixes paths for the
/es/ subfolder. It exits with an error if any English fragment is missing,
which means the English page changed and es_strings.py needs updating.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from es_strings import PAIRS  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent

# Structural edits: exact fragments that must each match once.
STRUCTURE = [
    ('<html lang="en">', '<html lang="es">'),
    ('<link rel="alternate" hreflang="es" href="es/">', '<link rel="alternate" hreflang="en" href="../">'),
    # The English page redirects returning Spanish visitors; the Spanish page never redirects.
    ('''    // Send returning visitors who chose Spanish straight to the Spanish page.
    try {
      if (localStorage.getItem("ra-lang") === "es" && !/[?&]lang=en/.test(location.search)) {
        location.replace("es/" + location.hash);
      }
    } catch (e) {}
''', ""),
    ('<a href="./" hreflang="en" lang="en" data-lang="en" aria-label="English" aria-current="true">EN</a>',
     '<a href="../?lang=en" hreflang="en" lang="en" data-lang="en" aria-label="English">EN</a>'),
    ('<a href="es/" hreflang="es" lang="es" data-lang="es" aria-label="Español">ES</a>',
     '<a href="./" hreflang="es" lang="es" data-lang="es" aria-label="Español" aria-current="true">ES</a>'),
    ('<a href="es/" hreflang="es" lang="es" data-lang="es">Ver en español</a>',
     '<a href="../?lang=en" hreflang="en" lang="en" data-lang="en">View in English</a>'),
    ('<input type="hidden" name="language" value="en">', '<input type="hidden" name="language" value="es">'),
]

# Paths: /es/ is one folder down.
PATHS = [
    ('src="assets/', 'src="../assets/'),
    ('href="assets/', 'href="../assets/'),
    ('content="assets/', 'content="../assets/'),
]


def main():
    html = (ROOT / "index.html").read_text()
    problems = []

    for en, es in STRUCTURE:
        n = html.count(en)
        if n != 1:
            problems.append(f"structure fragment found {n}x: {en[:70]!r}")
        html = html.replace(en, es)

    # Longest first so a short fragment never clips part of a longer one.
    for en, es in sorted(PAIRS, key=lambda p: len(p[0]), reverse=True):
        if en not in html:
            problems.append(f"missing English fragment: {en[:70]!r}")
        html = html.replace(en, es)

    for old, new in PATHS:
        html = html.replace(old, new)

    if problems:
        print("es/index.html NOT written:\n  " + "\n  ".join(problems), file=sys.stderr)
        sys.exit(1)

    out = ROOT / "es" / "index.html"
    out.parent.mkdir(exist_ok=True)
    banner = "<!-- Generated by tools/build_es.py from index.html. Edit tools/es_strings.py, not this file. -->\n"
    out.write_text(html.replace("<!doctype html>\n", "<!doctype html>\n" + banner, 1))
    print(f"wrote {out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
