"""English → Spanish copy for es/index.html.

Each pair is an exact fragment of index.html and its Spanish replacement.
build_es.py fails if any English fragment is no longer found, so edits to
the English page can't silently leave the Spanish page stale.

Tone: formal "usted", neutral Latin American Spanish, "concreto" (not
"cemento"). Have a native speaker (ideally the owner) review before launch.
"""

PAIRS = [
    # ---- <head> ------------------------------------------------------------
    ("<title>R&amp;A Concrete LLC | Concrete Driveways, Patios &amp; Slabs in Metro Atlanta</title>",
     "<title>R&amp;A Concrete LLC | Entradas de autos, patios y losas de concreto en Metro Atlanta</title>"),
    ('content="R&amp;A Concrete LLC pours concrete driveways, patios, walkways and slabs across metro Atlanta, Georgia. Request an estimate for your project."',
     'content="R&amp;A Concrete LLC hace entradas de autos, patios, caminos y losas de concreto en todo el área metropolitana de Atlanta, Georgia. Solicite un estimado para su proyecto."'),
    ('content="R&amp;A Concrete LLC | Concrete Flatwork in Metro Atlanta"',
     'content="R&amp;A Concrete LLC | Trabajos de concreto en Metro Atlanta"'),
    ('content="Driveways, patios, walkways and slabs across metro Atlanta, Georgia. Request an estimate."',
     'content="Entradas de autos, patios, caminos y losas en el área metropolitana de Atlanta, Georgia. Solicite un estimado."'),
    ('content="R&amp;A Concrete LLC logo on a concrete slab texture"',
     'content="Logotipo de R&amp;A Concrete LLC sobre una textura de losa de concreto"'),
    ('"description": "Concrete pouring company serving metro Atlanta, Georgia."',
     '"description": "Empresa de concreto que atiende el área metropolitana de Atlanta, Georgia."'),

    # ---- Header ------------------------------------------------------------
    ("Skip to content</a>", "Saltar al contenido</a>"),
    ('aria-label="R&amp;A Concrete LLC, back to top"', 'aria-label="R&amp;A Concrete LLC, volver arriba"'),
    ('aria-label="Primary"', 'aria-label="Principal"'),
    ('data-n="01">Services</a>', 'data-n="01">Servicios</a>'),
    ('data-n="02">Work</a>', 'data-n="02">Trabajos</a>'),
    ('data-n="04">Process</a>', 'data-n="04">Proceso</a>'),
    ('data-n="05">Service Area</a>', 'data-n="05">Área de servicio</a>'),
    ('data-n="06">FAQ</a>', 'data-n="06">Preguntas</a>'),
    ("Call (470) 392-0670</a>", "Llame al (470) 392-0670</a>"),
    ('<span class="visually-hidden">Call R&amp;A Concrete</span>',
     '<span class="visually-hidden">Llamar a R&amp;A Concrete</span>'),
    ('<span class="visually-hidden">Menu</span>', '<span class="visually-hidden">Menú</span>'),
    ("Request an Estimate", "Solicite un estimado"),

    # ---- Hero --------------------------------------------------------------
    ("Concrete flatwork &middot; Metro Atlanta, GA", "Trabajos de concreto &middot; Metro Atlanta, GA"),
    ("Concrete poured right. <em>Finished clean.</em>", "Concreto bien hecho. <em>Acabado limpio.</em>"),
    ("R&amp;A Concrete pours driveways, patios, walkways and slabs for homes and properties across metro Atlanta. Tell us about your project and we&rsquo;ll follow up to talk through the site, the scope and an estimate.",
     "R&amp;A Concrete hace entradas de autos, patios, caminos y losas para casas y propiedades en todo el área metropolitana de Atlanta. Cuéntenos sobre su proyecto y nos comunicaremos con usted para hablar del terreno, del trabajo y del estimado."),
    ('<p class="lang-note"><span lang="es">Se habla español.</span> Call or write in English or Spanish.</p>',
     '<p class="lang-note"><span>Hablamos español.</span> Llame o escríbanos en español o en inglés.</p>'),
    ('<ul class="hero-services" aria-label="Services">', '<ul class="hero-services" aria-label="Servicios">'),
    ("<li>Driveways</li>", "<li>Entradas de autos</li>"),
    ("<li>Patios</li>", "<li>Patios</li>"),
    ("<li>Walkways</li>", "<li>Caminos</li>"),
    ("<li>Slabs</li>", "<li>Losas</li>"),
    (">Saw-cut control joint</span>", ">Junta de control cortada</span>"),
    (">Broom finish</span>", ">Acabado escobillado</span>"),
    (">Wet &mdash; floated &amp; troweled</span>", ">Fresco &mdash; aplanado y allanado</span>"),
    ("<span>Fig. 1 &mdash; Wet pour to finished slab</span>", "<span>Fig. 1 &mdash; Del concreto fresco a la losa terminada</span>"),
    ("<span>Illustration only</span>", "<span>Solo ilustración</span>"),

    # ---- Services ----------------------------------------------------------
    ("01 &mdash; Services", "01 &mdash; Servicios"),
    ("Flatwork for the way you use your property.", "Concreto pensado para el uso de su propiedad."),
    ("Residential and light commercial concrete, planned around drainage, daily use and the ground it sits on.",
     "Concreto residencial y comercial ligero, planeado según el drenaje, el uso diario y el terreno donde se coloca."),
    ("Proposed service list &mdash; owner to confirm", "Lista de servicios propuesta &mdash; confirmar con el dueño"),
    ('aria-label="Typical scope"', 'aria-label="Trabajos típicos"'),
    ("<h3>Driveways</h3>", "<h3>Entradas de autos</h3>"),
    ("New driveways, extensions and full replacements. Laid out with the slope, thickness and joint spacing your vehicles and drainage call for.",
     "Entradas nuevas, ampliaciones y reemplazos completos. Con la pendiente, el grosor y la separación de juntas que requieren sus vehículos y el drenaje."),
    ("<li>New pour</li><li>Tear-out &amp; replace</li><li>Extensions</li><li>Aprons</li>",
     "<li>Colado nuevo</li><li>Demolición y reemplazo</li><li>Ampliaciones</li><li>Rampas de entrada</li>"),
    ("<h3>Patios</h3>", "<h3>Patios</h3>"),
    ("Outdoor living space off the back door or out in the yard, sized for the furniture, grill or fire pit you actually plan to put there.",
     "Espacio al aire libre junto a la puerta trasera o en el jardín, del tamaño adecuado para los muebles, el asador o la fogata que piensa poner."),
    ("<li>Back patios</li><li>Pads for outdoor kitchens</li><li>Extensions</li>",
     "<li>Patios traseros</li><li>Bases para cocinas exteriores</li><li>Ampliaciones</li>"),
    ("<h3>Walkways &amp; sidewalks</h3>", "<h3>Caminos y aceras</h3>"),
    ("Paths from driveway to door, side-yard runs and garden walks. Clean edges, even steps and a surface that sheds water.",
     "Caminos de la entrada a la puerta, pasillos laterales y senderos de jardín. Bordes limpios, escalones parejos y una superficie que escurre el agua."),
    ("<li>Front walks</li><li>Side paths</li><li>Steps &amp; landings</li>",
     "<li>Caminos al frente</li><li>Pasillos laterales</li><li>Escalones y descansos</li>"),
    ("<h3>Slabs &amp; pads</h3>", "<h3>Losas y bases</h3>"),
    ("Level bases for garages, sheds, workshops, HVAC and generator pads. Formed square, with the base prepared for the load it will carry.",
     "Bases niveladas para garajes, bodegas, talleres, equipos de aire acondicionado y generadores. Cimbradas a escuadra, con la base preparada para el peso que van a cargar."),
    ("<li>Garage &amp; shed slabs</li><li>Equipment pads</li><li>Footings</li>",
     "<li>Losas para garaje y bodega</li><li>Bases para equipos</li><li>Zapatas</li>"),
    ("<h3>Repair &amp; replacement</h3>", "<h3>Reparación y reemplazo</h3>"),
    ("When cracked, sunken or heaved sections need to come out, we&rsquo;ll look at what caused it before recommending a repair or a replacement.",
     "Cuando hay secciones agrietadas, hundidas o levantadas, primero revisamos la causa y después le recomendamos reparar o reemplazar."),
    ("<li>Section replacement</li><li>Removal &amp; haul-off</li>",
     "<li>Reemplazo de secciones</li><li>Demolición y retiro de escombro</li>"),

    # ---- Work --------------------------------------------------------------
    ("02 &mdash; Work", "02 &mdash; Trabajos"),
    ("The finished surface is the proof.", "La superficie terminada es la prueba."),
    ("This gallery is reserved for R&amp;A&rsquo;s own project photography. Each project will show the surface up close, alongside the details that matter when you&rsquo;re comparing contractors.",
     "Esta galería está reservada para fotos de proyectos propios de R&amp;A. Cada proyecto mostrará la superficie de cerca, junto con los detalles que importan al comparar contratistas."),
    ("Placeholders &mdash; real project photos needed", "Espacios reservados &mdash; faltan fotos reales"),
    ('<span class="photo-tag">Photo placeholder</span>', '<span class="photo-tag">Foto pendiente</span>'),
    ('<span class="photo-mono">Texture study</span>', '<span class="photo-mono">Estudio de textura</span>'),
    ('<span class="photo-mono">Close-up: edge &amp; joint detail</span>', '<span class="photo-mono">De cerca: bordes y juntas</span>'),
    ("<h3>Driveway replacement</h3>", "<h3>Reemplazo de entrada de autos</h3>"),
    ("<h3>Backyard patio</h3>", "<h3>Patio trasero</h3>"),
    ("<h3>Garage slab</h3>", "<h3>Losa de garaje</h3>"),
    ("<h3>Front walkway</h3>", "<h3>Camino al frente</h3>"),
    ("<h3>Surface detail</h3>", "<h3>Detalle de superficie</h3>"),
    ("<dt>Location</dt><dd>[City], GA</dd>", "<dt>Ubicación</dt><dd>[Ciudad], GA</dd>"),
    ("<dt>Scope</dt><dd>[To add]</dd>", "<dt>Trabajo</dt><dd>[Por agregar]</dd>"),
    ("<dt>Finish</dt><dd>[To add]</dd>", "<dt>Acabado</dt><dd>[Por agregar]</dd>"),

    # ---- Why R&A -----------------------------------------------------------
    ("03 &mdash; Why R&amp;A", "03 &mdash; Por qué R&amp;A"),
    ("What you see is the last step. What&rsquo;s under it matters more.",
     "Lo que usted ve es el último paso. Lo que hay debajo importa más."),
    ("Good concrete comes down to preparation, timing and finishing. We&rsquo;d rather take the extra hour on the base <span>than leave you a surface that fails early.</span>",
     "Un buen concreto depende de la preparación, el tiempo y el acabado. Preferimos dedicarle una hora más a la base <span>que dejarle una superficie que falle antes de tiempo.</span>"),
    ("Proposed priorities &mdash; owner to confirm wording", "Prioridades propuestas &mdash; confirmar texto con el dueño"),
    ("<h3>The base comes first</h3>", "<h3>Primero, la base</h3>"),
    ("Most concrete problems start below the surface. We look at soil, grade and drainage before we set forms, and prepare the base for what the slab will carry.",
     "La mayoría de los problemas del concreto empiezan debajo de la superficie. Revisamos el suelo, el nivel y el drenaje antes de poner la cimbra, y preparamos la base para el peso que va a cargar la losa."),
    ("<h3>Joints placed on purpose</h3>", "<h3>Juntas bien planeadas</h3>"),
    ("Concrete moves as it cures and ages. Control joints are laid out so that movement happens along clean lines, not across the middle of a panel.",
     "El concreto se mueve mientras fragua y con los años. Las juntas de control se colocan para que ese movimiento siga líneas limpias y no atraviese el centro de un tablero."),
    ("<h3>Edges and finish you&rsquo;ll notice</h3>", "<h3>Bordes y acabado que se notan</h3>"),
    ("Square forms, tooled edges and a consistent finish from one end of the pour to the other. The details you&rsquo;ll see every time you pull in.",
     "Cimbra a escuadra, bordes boleados y un acabado parejo de un extremo al otro. Los detalles que verá cada vez que llegue a casa."),
    ("<h3>A plan you can follow</h3>", "<h3>Un plan claro</h3>"),
    ("You&rsquo;ll know the scope, what the weather could change, and what to expect on pour day, so there are no surprises when the truck arrives.",
     "Sabrá qué incluye el trabajo, qué podría cambiar por el clima y qué esperar el día del colado, para que no haya sorpresas cuando llegue la revolvedora."),
    ("<h3>A clean site at the end</h3>", "<h3>Un lugar limpio al terminar</h3>"),
    ("Forms pulled, debris cleared and clear guidance on when the new surface is ready for foot traffic and vehicles.",
     "Cimbra retirada, escombro recogido e indicaciones claras de cuándo se puede caminar y pasar con vehículos sobre el concreto nuevo."),

    # ---- Process -----------------------------------------------------------
    ("04 &mdash; Process", "04 &mdash; Proceso"),
    ("From first call to a finished surface.", "De la primera llamada a la superficie terminada."),
    ("Six steps, each one finished before the next begins. Timing depends on your project, the site and the weather, and we&rsquo;ll walk you through it up front.",
     "Seis pasos, y cada uno se termina antes de empezar el siguiente. Los tiempos dependen de su proyecto, del terreno y del clima; se los explicamos desde el principio."),
    ('<span class="step-n">Step ', '<span class="step-n">Paso '),
    ("<h3>Inquiry</h3>", "<h3>Solicitud</h3>"),
    ("Send the estimate request with your location and a few words about the project. Photos help.",
     "Envíe la solicitud de estimado con su ubicación y unas palabras sobre el proyecto. Las fotos ayudan."),
    ("<h3>Site assessment</h3>", "<h3>Visita al terreno</h3>"),
    ("We look at the area, access, grade, drainage and any existing concrete that has to come out.",
     "Revisamos el área, el acceso, el nivel, el drenaje y cualquier concreto existente que haya que quitar."),
    ("<h3>Scope &amp; estimate</h3>", "<h3>Alcance y estimado</h3>"),
    ("You get a clear scope: dimensions, prep, finish and what the estimate includes.",
     "Recibe un alcance claro: medidas, preparación, acabado y qué incluye el estimado."),
    ("<h3>Scheduling</h3>", "<h3>Programación</h3>"),
    ("We set a pour date and plan around the forecast. If the weather turns, we&rsquo;ll tell you early.",
     "Fijamos la fecha del colado según el pronóstico. Si el clima cambia, le avisamos con tiempo."),
    ("<h3>Form &amp; pour</h3>", "<h3>Cimbra y colado</h3>"),
    ("Base prepared, forms set and checked, then the pour, screeding, floating and finishing.",
     "Base preparada, cimbra colocada y revisada, y luego el colado, el reglado, el aplanado y el acabado."),
    ("<h3>Cure &amp; walkthrough</h3>", "<h3>Fraguado y entrega</h3>"),
    ("Joints cut, forms stripped, site cleaned. We walk it with you and explain care during curing.",
     "Juntas cortadas, cimbra retirada y lugar limpio. Lo revisamos con usted y le explicamos los cuidados durante el fraguado."),
    ("Proposed process &mdash; owner to confirm", "Proceso propuesto &mdash; confirmar con el dueño"),

    # ---- Service area ------------------------------------------------------
    ("05 &mdash; Service area", "05 &mdash; Área de servicio"),
    ("Based in metro Atlanta. Working across it.", "Con base en Metro Atlanta. Trabajamos en toda el área."),
    ("R&amp;A Concrete serves homeowners and property owners in the metro Atlanta area.",
     "R&amp;A Concrete atiende a dueños de casas y propiedades en el área metropolitana de Atlanta."),
    ("Not sure whether your address is in range? Include your city or ZIP in the estimate request and we&rsquo;ll let you know.",
     "¿No sabe si su dirección está dentro del área? Incluya su ciudad o código postal en la solicitud y le avisamos."),
    ("Projects outside the core metro area may be possible depending on size and scheduling.",
     "Los proyectos fuera del área metropolitana pueden ser posibles según el tamaño y la agenda."),
    ("            Check your location\n", "            Consulte su ubicación\n"),
    ('<title id="map-title">Diagram of metro Atlanta</title>', '<title id="map-title">Diagrama del área metropolitana de Atlanta</title>'),
    ("Schematic showing the I-285 perimeter and major interstates around Atlanta. Not to scale; exact coverage to be confirmed.",
     "Esquema del periférico I-285 y las principales autopistas alrededor de Atlanta. No está a escala; la cobertura exacta está por confirmar."),
    ('fill="#a8432a">METRO ATLANTA (APPROX.)</text>', 'fill="#a8432a">METRO ATLANTA (APROX.)</text>'),
    ("Schematic, not to scale &mdash; coverage limits to be confirmed", "Esquema, no está a escala &mdash; límites de cobertura por confirmar"),

    # ---- FAQ ---------------------------------------------------------------
    ("06 &mdash; FAQ", "06 &mdash; Preguntas frecuentes"),
    ("Straight answers before you ask for a number.", "Respuestas claras antes de pedir un precio."),
    ("Something not covered here? Put it in the project description and we&rsquo;ll answer it directly.",
     "¿Tiene otra pregunta? Escríbala en la descripción del proyecto y se la contestamos directamente."),
    ("How much will my project cost?", "¿Cuánto costará mi proyecto?"),
    ("It depends on the size of the area, site access, whether old concrete has to be removed, how much base preparation is needed, thickness and reinforcement, and the finish you choose. We don&rsquo;t quote a price without understanding the site. Send the request and we&rsquo;ll follow up to set up an estimate.",
     "Depende del tamaño del área, el acceso al terreno, si hay que quitar concreto viejo, cuánta preparación necesita la base, el grosor, el refuerzo y el acabado que elija. No damos un precio sin conocer el terreno. Envíe la solicitud y nos comunicaremos para preparar un estimado."),
    ("Do you remove old concrete?", "¿Quitan el concreto viejo?"),
    ("Many replacement jobs start with tear-out and haul-off. Mention existing concrete in your request so it&rsquo;s included in the assessment.",
     "Muchos reemplazos empiezan con la demolición y el retiro del escombro. Mencione el concreto existente en su solicitud para incluirlo en la evaluación."),
    ("Owner to confirm tear-out &amp; disposal services", "Confirmar con el dueño: demolición y retiro de escombro"),
    ("When can I walk or drive on new concrete?", "¿Cuándo puedo caminar o pasar con el carro sobre el concreto nuevo?"),
    ("It depends on the mix, the thickness, temperature and humidity. Concrete keeps gaining strength for weeks after it&rsquo;s poured, so rather than giving a one-size-fits-all number, we&rsquo;ll tell you what applies to your pour before we leave.",
     "Depende de la mezcla, el grosor, la temperatura y la humedad. El concreto sigue ganando resistencia durante semanas después del colado, así que en lugar de darle un número general, le diremos lo que aplica a su colado antes de irnos."),
    ("Will my concrete crack?", "¿Se va a agrietar mi concreto?"),
    ("Honestly, concrete can crack. It shrinks as it cures and moves with temperature and the ground below. Good base preparation, correct joint spacing and proper curing go a long way toward controlling where cracking happens and keeping it minor.",
     "Siendo honestos, el concreto puede agrietarse. Se contrae al fraguar y se mueve con la temperatura y el suelo. Una buena base, la separación correcta de juntas y un buen curado ayudan mucho a controlar dónde aparecen las grietas y a que sean menores."),
    ("What happens if it rains on pour day?", "¿Qué pasa si llueve el día del colado?"),
    ("Weather has a real effect on concrete. We watch the forecast ahead of the pour and will reschedule if conditions put the finish at risk. We&rsquo;ll talk to you as soon as a change looks likely.",
     "El clima sí afecta al concreto. Revisamos el pronóstico antes del colado y cambiamos la fecha si las condiciones ponen en riesgo el acabado. Le avisamos en cuanto un cambio parezca probable."),
    ("Do I need a permit?", "¿Necesito un permiso?"),
    ("Permit requirements vary by city, county and project type. Driveway aprons and work near the street often have their own rules. We&rsquo;ll talk through what applies to your location during the assessment.",
     "Los permisos varían según la ciudad, el condado y el tipo de proyecto. Las rampas de entrada y los trabajos junto a la calle suelen tener sus propias reglas. En la visita le explicamos qué aplica en su ubicación."),
    ("Owner to confirm who handles permitting", "Confirmar con el dueño quién tramita los permisos"),
    ("Can I talk to you in Spanish?", "¿Puedo hablar con ustedes en español?"),
    ('Yes. <span lang="es">Hablamos español.</span> Call <a href="tel:+14703920670">(470) 392-0670</a> or fill out the estimate request in Spanish, and we&rsquo;ll work with you in whichever language you prefer.',
     'Sí. El dueño habla español. Llame al <a href="tel:+14703920670">(470) 392-0670</a> o llene la solicitud de estimado en español, y lo atendemos en el idioma que usted prefiera.'),
    ("Are you licensed and insured?", "¿Tienen licencia y seguro?"),
    ("License and insurance details will be listed here once confirmed. You&rsquo;re always welcome to ask for documentation before work begins.",
     "Los datos de licencia y seguro aparecerán aquí cuando estén confirmados. Siempre puede pedirnos la documentación antes de empezar el trabajo."),
    ("Owner to provide verified license &amp; insurance details", "El dueño debe proporcionar los datos verificados de licencia y seguro"),

    # ---- Estimate ----------------------------------------------------------
    ("07 &mdash; Request an estimate", "07 &mdash; Solicite un estimado"),
    ("Tell us about your project.", "Cuéntenos sobre su proyecto."),
    ("Five quick fields. The more you tell us about the site, the more useful our first conversation will be.",
     "Cinco datos rápidos. Mientras más nos cuente del terreno, más útil será nuestra primera conversación."),
    ('aria-label="What happens next"', 'aria-label="Qué sigue"'),
    ("We review your request and location.", "Revisamos su solicitud y ubicación."),
    ("We contact you to ask questions and arrange a site visit.", "Nos comunicamos con usted para hacerle preguntas y programar una visita."),
    ("You receive a scope and estimate for your project.", "Recibe el alcance y el estimado de su proyecto."),
    ("<p>Prefer to talk it through?</p>", "<p>¿Prefiere hablar por teléfono?</p>"),
    ('<p class="call-card-note"><span lang="es">Se habla español.</span></p>', '<p class="call-card-note">Hablamos español</p>'),
    ("<strong>Demo form.</strong> This form isn&rsquo;t connected to R&amp;A yet, so requests submitted here are not sent.",
     "<strong>Formulario de demostración.</strong> Este formulario todavía no está conectado con R&amp;A, así que las solicitudes que envíe aquí no llegan."),
    ('Name <span class="req"', 'Nombre <span class="req"'),
    ("Please enter your name.", "Escriba su nombre."),
    ('Project location <span class="req"', 'Ubicación del proyecto <span class="req"'),
    ("City or ZIP code is enough.", "Basta con la ciudad o el código postal."),
    ("Please enter a city or ZIP code.", "Escriba una ciudad o código postal."),
    ('Phone <span class="opt">(phone or email)</span>', 'Teléfono <span class="opt">(teléfono o correo)</span>'),
    ('Email <span class="opt">(phone or email)</span>', 'Correo electrónico <span class="opt">(teléfono o correo)</span>'),
    ("Please check the email address.", "Revise el correo electrónico."),
    ("Please give us a phone number or an email so we can reach you.",
     "Déjenos un teléfono o un correo electrónico para poder comunicarnos con usted."),
    ('Project type <span class="req"', 'Tipo de proyecto <span class="req"'),
    ('<option value="">Choose one</option>', '<option value="">Elija uno</option>'),
    ("<option>Driveway</option>", '<option value="Driveway">Entrada de autos</option>'),
    ("<option>Patio</option>", '<option value="Patio">Patio</option>'),
    ("<option>Walkway or sidewalk</option>", '<option value="Walkway or sidewalk">Camino o acera</option>'),
    ("<option>Slab or pad</option>", '<option value="Slab or pad">Losa o base</option>'),
    ("<option>Repair or replacement</option>", '<option value="Repair or replacement">Reparación o reemplazo</option>'),
    ("<option>Something else / not sure</option>", '<option value="Something else / not sure">Otro / no estoy seguro</option>'),
    ("Please choose a project type.", "Elija un tipo de proyecto."),
    ('Project description <span class="req"', 'Descripción del proyecto <span class="req"'),
    ("Rough size, what&rsquo;s there now, and anything you&rsquo;re unsure about.",
     "Tamaño aproximado, qué hay ahora y cualquier duda que tenga."),
    ("Please add a short description of the project.", "Agregue una breve descripción del proyecto."),
    ("Required. We use your details only to respond to this request.",
     "Obligatorio. Usamos sus datos solo para responder a esta solicitud."),

    # ---- Footer ------------------------------------------------------------
    ("Concrete driveways, patios, walkways and slabs across metro Atlanta, Georgia.",
     "Entradas de autos, patios, caminos y losas de concreto en el área metropolitana de Atlanta, Georgia."),
    ("<h2>Explore</h2>", "<h2>Explorar</h2>"),
    ('<li><a href="#services">Services</a></li>', '<li><a href="#services">Servicios</a></li>'),
    ('<li><a href="#work">Work</a></li>', '<li><a href="#work">Trabajos</a></li>'),
    ('<li><a href="#process">Process</a></li>', '<li><a href="#process">Proceso</a></li>'),
    ('<li><a href="#faq">FAQ</a></li>', '<li><a href="#faq">Preguntas</a></li>'),
    ("<h2>Contact</h2>", "<h2>Contacto</h2>"),
    ('<li><a href="#estimate">Estimate request</a></li>', '<li><a href="#estimate">Solicitud de estimado</a></li>'),
    ("<li>Metro Atlanta, Georgia</li>", "<li>Metro Atlanta, Georgia</li>"),
    ('<li><span lang="es">Se habla español</span></li>', "<li>Hablamos español</li>"),
    ('<a href="brand.html">Brand guidelines</a>', '<a href="../brand.html" lang="en" hreflang="en">Brand guidelines (EN)</a>'),
    ('<span>Call</span></a>', '<span>Llamar</span></a>'),
]
