"""English → Spanish copy for es/index.html.

Each pair is an exact fragment of index.html and its Spanish replacement.
build_es.py fails if any English fragment is no longer found, so edits to
the English page can't silently leave the Spanish page stale.

Tone: formal "usted", neutral Latin American Spanish, "concreto" (not
"cemento"). Have a native speaker (ideally the owner) review before launch.
"""

PAIRS = [
    ('Skip to content</a>',
     'Saltar al contenido</a>'),
    ('aria-label="Primary"',
     'aria-label="Principal"'),
    ('Call (470) 392-0670</a>',
     'Llame al (470) 392-0670</a>'),
    ('<span class="visually-hidden">Call R&amp;A Concrete</span>',
     '<span class="visually-hidden">Llamar a R&amp;A Concrete</span>'),
    ('<span class="visually-hidden">Menu</span>',
     '<span class="visually-hidden">Menú</span>'),
    ('Request an Estimate',
     'Solicite un estimado'),
    ('Concrete poured right. <em>Finished clean.</em>',
     'Concreto bien hecho. <em>Acabado limpio.</em>'),
    ('<ul class="hero-services" aria-label="Services">',
     '<ul class="hero-services" aria-label="Servicios">'),
    ('<li>Driveways</li>',
     '<li>Entradas de autos</li>'),
    ('<li>Patios</li>',
     '<li>Patios</li>'),
    ('>Saw-cut control joint</span>',
     '>Junta de control cortada</span>'),
    ('>Broom finish</span>',
     '>Acabado escobillado</span>'),
    ('>Wet &mdash; floated &amp; troweled</span>',
     '>Fresco &mdash; aplanado y allanado</span>'),
    ('<span>Fig. 1 &mdash; Wet pour to finished slab</span>',
     '<span>Fig. 1 &mdash; Del concreto fresco a la losa terminada</span>'),
    ('<span>Illustration only</span>',
     '<span>Solo ilustración</span>'),
    ('01 &mdash; Services',
     '01 &mdash; Servicios'),
    ('aria-label="Typical scope"',
     'aria-label="Trabajos típicos"'),
    ('<h3>Driveways</h3>',
     '<h3>Entradas de autos</h3>'),
    ('<h3>Patios</h3>',
     '<h3>Patios</h3>'),
    ('Outdoor living space off the back door or out in the yard, sized for the furniture, grill or fire pit you actually plan to put there.',
     'Espacio al aire libre junto a la puerta trasera o en el jardín, del tamaño adecuado para los muebles, el asador o la fogata que piensa poner.'),
    ('02 &mdash; Work',
     '02 &mdash; Trabajos'),
    ('The finished surface is the proof.',
     'La superficie terminada es la prueba.'),
    ('From first call to a finished surface.',
     'De la primera llamada a la superficie terminada.'),
    ('<span class="step-n">Step ',
     '<span class="step-n">Paso '),
    ('<h3>Inquiry</h3>',
     '<h3>Solicitud</h3>'),
    ('<h3>Site assessment</h3>',
     '<h3>Visita al terreno</h3>'),
    ('<h3>Scope &amp; estimate</h3>',
     '<h3>Alcance y estimado</h3>'),
    ('<h3>Scheduling</h3>',
     '<h3>Programación</h3>'),
    ('<h3>Form &amp; pour</h3>',
     '<h3>Cimbra y colado</h3>'),
    ('<h3>Cure &amp; walkthrough</h3>',
     '<h3>Fraguado y entrega</h3>'),
    ('Proposed process &mdash; owner to confirm',
     'Proceso propuesto &mdash; confirmar con el dueño'),
    ('Based in metro Atlanta. Working across it.',
     'Con base en Metro Atlanta. Trabajamos en toda el área.'),
    ('R&amp;A Concrete serves homeowners and property owners in the metro Atlanta area.',
     'R&amp;A Concrete atiende a dueños de casas y propiedades en el área metropolitana de Atlanta.'),
    ('            Check your location\n',
     '            Consulte su ubicación\n'),
    ('<title id="map-title">Diagram of metro Atlanta</title>',
     '<title id="map-title">Diagrama del área metropolitana de Atlanta</title>'),
    ('Schematic showing the I-285 perimeter and major interstates around Atlanta. Not to scale; exact coverage to be confirmed.',
     'Esquema del periférico I-285 y las principales autopistas alrededor de Atlanta. No está a escala; la cobertura exacta está por confirmar.'),
    ('fill="#a8432a">METRO ATLANTA (APPROX.)</text>',
     'fill="#a8432a">METRO ATLANTA (APROX.)</text>'),
    ('Schematic, not to scale &mdash; coverage limits to be confirmed',
     'Esquema, no está a escala &mdash; límites de cobertura por confirmar'),
    ('Straight answers before you ask for a number.',
     'Respuestas claras antes de pedir un precio.'),
    ('How much will my project cost?',
     '¿Cuánto costará mi proyecto?'),
    ('Do you remove old concrete?',
     '¿Quitan el concreto viejo?'),
    ('Many replacement jobs start with tear-out and haul-off. Mention existing concrete in your request so it&rsquo;s included in the assessment.',
     'Muchos reemplazos empiezan con la demolición y el retiro del escombro. Mencione el concreto existente en su solicitud para incluirlo en la evaluación.'),
    ('Owner to confirm tear-out &amp; disposal services',
     'Confirmar con el dueño: demolición y retiro de escombro'),
    ('When can I walk or drive on new concrete?',
     '¿Cuándo puedo caminar o pasar con el carro sobre el concreto nuevo?'),
    ('Will my concrete crack?',
     '¿Se va a agrietar mi concreto?'),
    ('Honestly, concrete can crack. It shrinks as it cures and moves with temperature and the ground below. Good base preparation, correct joint spacing and proper curing go a long way toward controlling where cracking happens and keeping it minor.',
     'Siendo honestos, el concreto puede agrietarse. Se contrae al fraguar y se mueve con la temperatura y el suelo. Una buena base, la separación correcta de juntas y un buen curado ayudan mucho a controlar dónde aparecen las grietas y a que sean menores.'),
    ('What happens if it rains on pour day?',
     '¿Qué pasa si llueve el día del colado?'),
    ('Do I need a permit?',
     '¿Necesito un permiso?'),
    ('Owner to confirm who handles permitting',
     'Confirmar con el dueño quién tramita los permisos'),
    ('Can I talk to you in Spanish?',
     '¿Puedo hablar con ustedes en español?'),
    ('Are you licensed and insured?',
     '¿Tienen licencia y seguro?'),
    ('Owner to provide verified license &amp; insurance details',
     'El dueño debe proporcionar los datos verificados de licencia y seguro'),
    ('Tell us about your project.',
     'Cuéntenos sobre su proyecto.'),
    ('aria-label="What happens next"',
     'aria-label="Qué sigue"'),
    ('<p class="call-card-note"><span lang="es">Se habla español.</span></p>',
     '<p class="call-card-note">Hablamos español</p>'),
    ('Name <span class="req"',
     'Nombre <span class="req"'),
    ('Please enter your name.',
     'Escriba su nombre.'),
    ('Project location <span class="req"',
     'Ubicación del proyecto <span class="req"'),
    ('City or ZIP code is enough.',
     'Basta con la ciudad o el código postal.'),
    ('Please enter a city or ZIP code.',
     'Escriba una ciudad o código postal.'),
    ('Phone <span class="opt">(phone or email)</span>',
     'Teléfono <span class="opt">(teléfono o correo)</span>'),
    ('Email <span class="opt">(phone or email)</span>',
     'Correo electrónico <span class="opt">(teléfono o correo)</span>'),
    ('Please check the email address.',
     'Revise el correo electrónico.'),
    ('Please give us a phone number or an email so we can reach you.',
     'Déjenos un teléfono o un correo electrónico para poder comunicarnos con usted.'),
    ('Project type <span class="req"',
     'Tipo de proyecto <span class="req"'),
    ('<option value="">Choose one</option>',
     '<option value="">Elija uno</option>'),
    ('<option>Driveway</option>',
     '<option value="Driveway">Entrada de autos</option>'),
    ('<option>Patio</option>',
     '<option value="Patio">Patio</option>'),
    ('<option>Something else / not sure</option>',
     '<option value="Something else / not sure">Otro / no estoy seguro</option>'),
    ('Please choose a project type.',
     'Elija un tipo de proyecto.'),
    ('Project description <span class="req"',
     'Descripción del proyecto <span class="req"'),
    ('Rough size, what&rsquo;s there now, and anything you&rsquo;re unsure about.',
     'Tamaño aproximado, qué hay ahora y cualquier duda que tenga.'),
    ('Please add a short description of the project.',
     'Agregue una breve descripción del proyecto.'),
    ('Required. We use your details only to respond to this request.',
     'Obligatorio. Usamos sus datos solo para responder a esta solicitud.'),
    ('<h2>Explore</h2>',
     '<h2>Explorar</h2>'),
    ('<li><a href="#services">Services</a></li>',
     '<li><a href="#services">Servicios</a></li>'),
    ('<li><a href="#work">Work</a></li>',
     '<li><a href="#work">Trabajos</a></li>'),
    ('<li><a href="#process">Process</a></li>',
     '<li><a href="#process">Proceso</a></li>'),
    ('<li><a href="#faq">FAQ</a></li>',
     '<li><a href="#faq">Preguntas</a></li>'),
    ('<h2>Contact</h2>',
     '<h2>Contacto</h2>'),
    ('<li><a href="#estimate">Estimate request</a></li>',
     '<li><a href="#estimate">Solicitud de estimado</a></li>'),
    ('<li>Metro Atlanta, Georgia</li>',
     '<li>Metro Atlanta, Georgia</li>'),
    ('<li><span lang="es">Se habla español</span></li>',
     '<li>Hablamos español</li>'),
    ('<span>Call</span></a>',
     '<span>Llamar</span></a>'),
    ('<title>R&amp;A Concrete Construction LLC | Driveways, Patios, Stamped Concrete &amp; Hardscape in Metro Atlanta</title>',
     '<title>R&amp;A Concrete Construction LLC | Entradas de autos, patios, concreto estampado y hardscape en Metro Atlanta</title>'),
    ('content="Residential and commercial concrete across metro Atlanta: driveways, patios, sidewalks, slabs, stamped and colored concrete, pavers, retaining walls and pool renovations. Call (470) 392-0670 or request an estimate."',
     'content="Concreto residencial y comercial en el área metropolitana de Atlanta: entradas de autos, patios, banquetas, losas, concreto estampado y de color, adoquines, muros de contención y renovación de albercas. Llame al (470) 392-0670 o solicite un estimado."'),
    ('content="R&amp;A Concrete Construction LLC | Residential &amp; Commercial Concrete in Metro Atlanta"',
     'content="R&amp;A Concrete Construction LLC | Concreto residencial y comercial en Metro Atlanta"'),
    ('content="Driveways, patios, stamped concrete, pavers, walls and pool renovations across metro Atlanta, Georgia. Se habla español."',
     'content="Entradas de autos, patios, concreto estampado, adoquines, muros y renovación de albercas en el área metropolitana de Atlanta, Georgia. Hablamos español."'),
    ('content="R&amp;A Concrete Construction LLC logo on a concrete slab texture"',
     'content="Logotipo de R&amp;A Concrete Construction LLC sobre una textura de losa de concreto"'),
    ('"description": "Residential and commercial concrete contractor serving metro Atlanta, Georgia."',
     '"description": "Contratista de concreto residencial y comercial en el área metropolitana de Atlanta, Georgia."'),
    ('aria-label="R&amp;A Concrete Construction LLC, back to top"',
     'aria-label="R&amp;A Concrete Construction LLC, volver arriba"'),
    ('<li>Stamped concrete</li>',
     '<li>Concreto estampado</li>'),
    ('<li>Hardscape</li>',
     '<li>Hardscape</li>'),
    ('<li>Walls</li>',
     '<li>Muros</li>'),
    ('Residential and commercial concrete.</h2>',
     'Concreto residencial y comercial.</h2>'),
    ('Don&rsquo;t see your project here? Ask us. We take on a wide range of concrete and hardscape work.',
     '¿No ve su proyecto aquí? Pregúntenos. Hacemos todo tipo de trabajos de concreto y hardscape.'),
    ('<li>New driveways</li><li>Extensions</li><li>Replacements</li>',
     '<li>Entradas nuevas</li><li>Ampliaciones</li><li>Reemplazos</li>'),
    ('<li>Back patios</li><li>Outdoor kitchen pads</li><li>Extensions</li>',
     '<li>Patios traseros</li><li>Bases para cocinas exteriores</li><li>Ampliaciones</li>'),
    ('<h3>Sidewalks &amp; walkways</h3>',
     '<h3>Banquetas y caminos</h3>'),
    ('Paths from driveway to door, side-yard runs and garden walks. Clean edges, even transitions and a surface that sheds water.',
     'Caminos de la entrada a la puerta, pasillos laterales y senderos de jardín. Bordes limpios, transiciones parejas y una superficie que escurre el agua.'),
    ('<li>Front walks</li><li>Side paths</li><li>Sidewalks</li>',
     '<li>Caminos al frente</li><li>Pasillos laterales</li><li>Banquetas</li>'),
    ('<h3>Slabs</h3>',
     '<h3>Losas</h3>'),
    ('<li>Garage &amp; shed slabs</li><li>Equipment pads</li>',
     '<li>Losas para garaje y bodega</li><li>Bases para equipos</li>'),
    ('<h3>Stamped &amp; colored concrete</h3>',
     '<h3>Concreto estampado y de color</h3>'),
    ('Pattern and color pressed into fresh concrete, for patios, walks and driveways that look like stone, slate or brick.',
     'Diseño y color aplicados al concreto fresco, para patios, caminos y entradas con apariencia de piedra, pizarra o ladrillo.'),
    ('<li>Stamped patterns</li><li>Colored concrete</li>',
     '<li>Diseños estampados</li><li>Concreto de color</li>'),
    ('<h3>Hardscape &amp; pavers</h3>',
     '<h3>Hardscape y adoquines</h3>'),
    ('Paver patios, walkways and borders, and the hardscape that ties an outdoor space together.',
     'Patios, caminos y bordes de adoquín, y el hardscape que le da unidad a un espacio exterior.'),
    ('<li>Paver patios</li><li>Walkways</li><li>Borders</li>',
     '<li>Patios de adoquín</li><li>Caminos</li><li>Bordes</li>'),
    ('<h3>Retaining walls, sitting walls &amp; fire pits</h3>',
     '<h3>Muros de contención, muros para sentarse y fogatas</h3>'),
    ('Retaining walls to hold back a slope, sitting walls to frame a patio, and a fire pit to finish it.',
     'Muros de contención para sostener una pendiente, muros para sentarse que enmarcan el patio y una fogata para completarlo.'),
    ('<li>Retaining walls</li><li>Sitting walls</li><li>Fire pits</li>',
     '<li>Muros de contención</li><li>Muros para sentarse</li><li>Fogatas</li>'),
    ('<h3>Pool renovations</h3>',
     '<h3>Renovación de albercas</h3>'),
    ('<option>Sidewalk or walkway</option>',
     '<option value="Sidewalk or walkway">Banqueta o camino</option>'),
    ('<option>Slab</option>',
     '<option value="Slab">Losa</option>'),
    ('<option>Stamped or colored concrete</option>',
     '<option value="Stamped or colored concrete">Concreto estampado o de color</option>'),
    ('<option>Pavers or hardscape</option>',
     '<option value="Pavers or hardscape">Adoquines o hardscape</option>'),
    ('<option>Retaining wall, sitting wall or fire pit</option>',
     '<option value="Retaining wall, sitting wall or fire pit">Muro de contención, muro para sentarse o fogata</option>'),
    ('<option>Pool renovation</option>',
     '<option value="Pool renovation">Renovación de alberca</option>'),
    ('<p>Residential and commercial concrete across metro Atlanta, Georgia. Driveways, patios, stamped concrete, hardscape and more.</p>',
     '<p>Concreto residencial y comercial en el área metropolitana de Atlanta, Georgia. Entradas de autos, patios, concreto estampado, hardscape y más.</p>'),
    ('>Project videos</a></li>',
     '>Videos de proyectos</a></li>'),
    ('Driveways, patios, sidewalks and slabs, plus stamped concrete, pavers, walls and pool renovations, for homes and businesses across metro Atlanta. Call, text or send us your project details to get an estimate started.',
     'Entradas de autos, patios, banquetas y losas, además de concreto estampado, adoquines, muros y renovación de albercas, para casas y negocios en todo el área metropolitana de Atlanta. Llame, mande un mensaje o envíenos los detalles de su proyecto para empezar su estimado.'),
    ('<p class="lang-note"><span lang="es">Se habla español.</span> Prefer to text? <a href="sms:+14703920670">Send us photos of your project</a>.</p>',
     '<p class="lang-note"><span>Hablamos español.</span> ¿Prefiere mandar un mensaje? <a href="sms:+14703920670">Envíenos fotos de su proyecto</a>.</p>'),
    ('<span class="hero-kicker">Concrete contractor &middot; Metro Atlanta, GA</span>',
     '<span class="hero-kicker">Contratista de concreto &middot; Metro Atlanta, GA</span>'),
    ('From everyday driveways and slabs to stamped finishes, walls and pool renovations, for homes and businesses across metro Atlanta.',
     'Desde entradas de autos y losas hasta acabados estampados, muros y renovación de albercas, para casas y negocios en todo el área metropolitana de Atlanta.'),
    ('New driveways, extensions and full replacements. Sized for your vehicles and shaped to drain.',
     'Entradas nuevas, ampliaciones y reemplazos completos. Del tamaño de sus vehículos y con la pendiente para drenar.'),
    ('Level bases for garages, sheds, workshops and equipment. Formed square and built for the load they carry.',
     'Bases niveladas para garajes, bodegas, talleres y equipos. Cimbradas a escuadra y hechas para el peso que cargan.'),
    ('Renovating the concrete and hardscape around an existing pool. Tell us what you have in mind.',
     'Renovación del concreto y el hardscape alrededor de una alberca existente. Cuéntenos qué tiene en mente.'),
    ('<h3>Finishes we offer</h3>',
     '<h3>Acabados que ofrecemos</h3>'),
    ('<h4>Broom finish</h4>',
     '<h4>Acabado escobillado</h4>'),
    ('The everyday standard for driveways and walks. A fine, even texture that gives grip in the rain.',
     'El acabado más común para entradas y caminos. Una textura fina y pareja que da agarre cuando llueve.'),
    ('<h4>Stamped &amp; colored</h4>',
     '<h4>Estampado y de color</h4>'),
    ('Pattern and color pressed into fresh concrete for the look of stone, slate or brick.',
     'Diseño y color aplicados al concreto fresco para lograr la apariencia de piedra, pizarra o ladrillo.'),
    ('<h4>Pavers</h4>',
     '<h4>Adoquines</h4>'),
    ('Individual units laid in a pattern, for patios, walkways and borders.',
     'Piezas individuales colocadas en un diseño, para patios, caminos y bordes.'),
    ('Illustrations of finish types, not photos of completed projects.',
     'Ilustraciones de tipos de acabado, no fotos de proyectos terminados.'),
    ('03 &mdash; Request an estimate',
     '03 &mdash; Solicite un estimado'),
    ('A few quick fields. The more you tell us about the site, the more useful our first conversation will be.',
     'Unos cuantos datos rápidos. Mientras más nos cuente del terreno, más útil será nuestra primera conversación.'),
    ('<li>We review your project and location.</li>',
     '<li>Revisamos su proyecto y ubicación.</li>'),
    ('<li>We get back to you with questions and next steps.</li>',
     '<li>Nos comunicamos con usted con preguntas y los siguientes pasos.</li>'),
    ('<li>You get an estimate for your project.</li>',
     '<li>Recibe un estimado para su proyecto.</li>'),
    ('<p>Prefer to talk or text?</p>',
     '<p>¿Prefiere llamar o mandar un mensaje?</p>'),
    ('href="sms:+14703920670">Text (470) 392-0670</a>',
     'href="sms:+14703920670">Mensaje al (470) 392-0670</a>'),
    ('Sending opens your email app with your details filled in, addressed to R&amp;A. Press send there to deliver it.',
     'Al enviar se abre su correo electrónico con sus datos ya escritos para R&amp;A. Presione enviar ahí para entregarlo.'),
    ('04 &mdash; Why it matters',
     '04 &mdash; Por qué importa'),
    ('What you see is the last step. <span>What&rsquo;s under it matters more.</span>',
     'Lo que usted ve es el último paso. <span>Lo que hay debajo importa más.</span>'),
    ('Good concrete comes down to preparation, timing and finishing. Five things decide whether a slab lasts.',
     'Un buen concreto depende de la preparación, el tiempo y el acabado. Cinco cosas deciden si una losa dura.'),
    ('<h3>The base</h3>',
     '<h3>La base</h3>'),
    ('Most concrete problems start below the surface, in soil, grade and drainage.',
     'La mayoría de los problemas empiezan debajo de la superficie: en el suelo, el nivel y el drenaje.'),
    ('<h3>The joints</h3>',
     '<h3>Las juntas</h3>'),
    ('Concrete moves as it cures. Control joints decide where that movement shows.',
     'El concreto se mueve al fraguar. Las juntas de control deciden dónde se nota ese movimiento.'),
    ('<h3>The finish</h3>',
     '<h3>El acabado</h3>'),
    ('Square forms, clean edges and an even finish from one end of the pour to the other.',
     'Cimbra a escuadra, bordes limpios y un acabado parejo de un extremo al otro.'),
    ('<h3>The weather</h3>',
     '<h3>El clima</h3>'),
    ('Rain, heat and cold all affect a pour, so timing matters as much as technique.',
     'La lluvia, el calor y el frío afectan el colado, así que el momento importa tanto como la técnica.'),
    ('<h3>The cure</h3>',
     '<h3>El fraguado</h3>'),
    ('New concrete keeps gaining strength for weeks. Early care protects the surface.',
     'El concreto nuevo sigue ganando resistencia durante semanas. Cuidarlo al principio protege la superficie.'),
    ('Ask us how each one applies to your project:',
     'Pregúntenos cómo aplica cada uno a su proyecto:'),
    ('05 &mdash; Process',
     '05 &mdash; Proceso'),
    ('The usual path for a project. Timing depends on the project, the site and the weather.',
     'El camino habitual de un proyecto. Los tiempos dependen del proyecto, el terreno y el clima.'),
    ('Call, text or send your project details with your location. Photos help.',
     'Llame, mande un mensaje o envíe los detalles de su proyecto con su ubicación. Las fotos ayudan.'),
    ('The area, access, grade, drainage and any existing concrete are assessed.',
     'Se revisan el área, el acceso, el nivel, el drenaje y cualquier concreto existente.'),
    ('A scope covering dimensions, prep, finish and what the estimate includes.',
     'Un alcance con medidas, preparación, acabado y qué incluye el estimado.'),
    ('A pour date is set around the forecast, since weather can move it.',
     'La fecha del colado se fija según el pronóstico, porque el clima puede cambiarla.'),
    ('Base prepared and forms set, then the pour, screeding, floating and finishing.',
     'Base preparada y cimbra colocada; luego el colado, el reglado, el aplanado y el acabado.'),
    ('Joints cut and forms stripped. Then a final look together and care tips for curing.',
     'Juntas cortadas y cimbra retirada. Después, una revisión final juntos y consejos para el fraguado.'),
    ('06 &mdash; Service area',
     '06 &mdash; Área de servicio'),
    ('Not sure whether your address is in range? Call or text with your city or ZIP and we&rsquo;ll let you know.',
     '¿No sabe si su dirección está dentro del área? Llame o mande un mensaje con su ciudad o código postal y le avisamos.'),
    ('For projects outside the core metro area, just ask.',
     'Para proyectos fuera del área metropolitana, pregúntenos.'),
    ('07 &mdash; FAQ',
     '07 &mdash; Preguntas frecuentes'),
    ('Something not covered here? Call, text or email and ask.',
     '¿Tiene otra pregunta? Llame, mande un mensaje o escríbanos.'),
    ('It depends on the size of the area, site access, whether old concrete has to be removed, how much base preparation is needed, thickness and reinforcement, and the finish you choose. An accurate price depends on seeing the site, so start with a call or an estimate request.',
     'Depende del tamaño del área, el acceso al terreno, si hay que quitar concreto viejo, cuánta preparación necesita la base, el grosor, el refuerzo y el acabado que elija. Un precio exacto depende de ver el terreno, así que empiece con una llamada o una solicitud de estimado.'),
    ('It depends on the mix, the thickness, temperature and humidity. Concrete keeps gaining strength for weeks after it&rsquo;s poured, so there&rsquo;s no one-size-fits-all number. Ask what applies to your pour.',
     'Depende de la mezcla, el grosor, la temperatura y la humedad. El concreto sigue ganando resistencia durante semanas después del colado, así que no hay un número único. Pregunte qué aplica a su colado.'),
    ('Weather has a real effect on concrete. Pour dates are planned around the forecast and can move if conditions would put the finish at risk.',
     'El clima sí afecta al concreto. Las fechas de colado se planean según el pronóstico y pueden cambiar si las condiciones ponen en riesgo el acabado.'),
    ('Permit requirements vary by city, county and project type. Driveway aprons and work near the street often have their own rules. Ask us what applies to your location.',
     'Los permisos varían según la ciudad, el condado y el tipo de proyecto. Las rampas de entrada y los trabajos junto a la calle suelen tener sus propias reglas. Pregúntenos qué aplica en su ubicación.'),
    ('Yes. <span lang="es">Hablamos español.</span> Call or text <a href="tel:+14703920670">(470) 392-0670</a>, or send your estimate request in Spanish.',
     'Sí. El dueño habla español. Llame o mande un mensaje al <a href="tel:+14703920670">(470) 392-0670</a>, o envíe su solicitud de estimado en español.'),
    ('Ask us for license and insurance documentation. It&rsquo;s a fair question to ask any contractor before work begins.',
     'Pídanos la documentación de licencia y seguro. Es una pregunta justa para cualquier contratista antes de empezar un trabajo.'),
    ('"knowsAbout": ["Concrete driveways", "Concrete patios", "Concrete slabs", "Sidewalks", "Stamped concrete", "Colored concrete", "Hardscape and pavers", "Retaining walls", "Sitting walls", "Fire pits", "Pool renovations"]',
     '"knowsAbout": ["Entradas de autos de concreto", "Patios de concreto", "Losas de concreto", "Banquetas", "Concreto estampado", "Concreto de color", "Hardscape y adoquines", "Muros de contención", "Muros para sentarse", "Fogatas", "Renovación de albercas"]'),
    ('<li><a href="sms:+14703920670">Text (470) 392-0670</a></li>',
     '<li><a href="sms:+14703920670">Mensaje al (470) 392-0670</a></li>'),
    ('See R&amp;A&rsquo;s recent projects on video, the best way to judge the finish up close.',
     'Vea los proyectos recientes de R&amp;A en video, la mejor manera de juzgar el acabado de cerca.'),
    ('Watch project videos<span class="visually-hidden"> (opens in a new tab)</span>',
     'Ver videos de proyectos<span class="visually-hidden"> (se abre en otra pestaña)</span>'),
    ('<span class="video-poster-tag">Video</span>',
     '<span class="video-poster-tag">Video</span>'),
    ('<span class="video-poster-cap">Recent projects &middot; R&amp;A Concrete</span>',
     '<span class="video-poster-cap">Proyectos recientes &middot; R&amp;A Concrete</span>'),
    ('Every surface starts with a choice of finish. Here are the three you&rsquo;ll see most.',
     'Cada superficie empieza con la elección del acabado. Estos son los tres más comunes.'),
]
